# Generated by Django 5.2.7 on 2025-11-08 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la séance')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('places_max', models.IntegerField(default=10, verbose_name='Places maximum')),
                ('statut', models.CharField(choices=[('PREVUE', 'Prévue'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PREVUE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='tutorat.matiere', verbose_name='Matière')),
                ('tuteur', models.ForeignKey(limit_choices_to={'role': 'TUTEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='seances_tuteur', to=settings.AUTH_USER_MODEL, verbose_name='Tuteur')),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['-date', '-heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée')], default='CONFIRMEE', max_length=20, verbose_name='Statut')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'ETUDIANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='tutorat.seance', verbose_name='Séance')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('etudiant', 'seance')},
            },
        ),
    ]
