# Generated by Django 5.2.8 on 2025-12-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='derniere_visite_forum',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière visite du forum'),
        ),
    ]
