# Generated by Django 5.2.8 on 2025-11-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorat', '0002_sujet_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doit_changer_mdp',
            field=models.BooleanField(default=False, verbose_name='Doit changer le mot de passe'),
        ),
    ]
